### DISCUSSION TITLE
Password authentication failed for user "teslamate"

### DISCUSSION THREAD

**Discussion by Toskache** [pkuehnel/TeslaSolarCharger#1180] [Q&A]
Hi,
 I am trying to setup TeslaSolarcharger with my E3/DC system.
Teslamate is running on a pi  with docker for 2,5 years - no problems here.

I add the following services to my docker-compose.yml:

```
  teslamateapi:
    image: tobiasehlert/teslamateapi:latest
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"
    restart: always
    depends_on:
      - database
    environment:
      - ENCRYPTION_KEY=hereisthekey
      - DATABASE_USER=teslamate
      - DATABASE_PASS=password
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto
      - TZ=Europe/Berlin ##You can change your Timezone here
      - ENABLE_COMMANDS=true
      - COMMANDS_ALL=true
      - API_TOKEN_DISABLE=true
    #ports:
    #  - 8080:8080

  teslasolarcharger:
    image: pkuehnel/teslasolarcharger:latest
    container_name: teslasolarcharger
    logging:
        driver: "json-file"
        options:
            max-file: "10"
            max-size: "100m"
    restart: always
    depends_on:
      - teslamateapi
    environment:
      # - Serilog__MinimumLevel__Default=Verbose #uncomment this line and recreate container with docker compose up -d for more detailed logs
      - TZ=Europe/Berlin ##You can change your Timezone here
    ports:
      - 7190:80
    volumes:
      - teslasolarcharger-configs:/app/configs

  modbusplugin:
    image: pkuehnel/teslasolarchargermodbusplugin:latest
    container_name: teslasolarcharger_modbusplugin
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"
    restart: always
    environment:
      - RequestBlockMilliseconds=0
    ports:
      - 7191:80
  ```

I am 100% sure, that the values of ENCRYPTION_KEY, DATABASE_USER, DATABASE_PASS, DATABASE_NAME and DATABASE_HOST are correct. I copied the values from the teslamate-service.

Unfortunaltely I get an DB-Connection-Error
 ```
teslasolarcharger  | [07-Apr-2024 17:16:27.065 INF TeslaSolarCharger.Server.Helper.BaseConfigurationConverter] Do not convert environment variables to json file as json already exists.
teslasolarcharger  | [07-Apr-2024 17:16:29.332 WRN Microsoft.EntityFrameworkCore.Model.Validation] Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data; this mode should only be enabled during development.
teslasolarcharger  | [07-Apr-2024 17:16:29.517 WRN Microsoft.EntityFrameworkCore.Model.Validation] The 'EnergyProvider' property 'EnergyProvider' on entity type 'ChargePrice' is configured with a database-generated default, but has no configured sentinel value. The database-generated default will always be used for inserts when the property has the value 'Octopus', since this is the CLR default for the 'EnergyProvider' type. Consider using a nullable type, using a nullable backing field, or setting the sentinel value for the property to ensure the database default is used when, and only when, appropriate. See https://aka.ms/efcore-docs-default-values for more information.
teslasolarcharger  | [07-Apr-2024 17:16:32.376 INF TeslaSolarCharger.Server.Services.CoreService] Backup for this version already created. No new backup needed.
teslasolarcharger  | [07-Apr-2024 17:16:32.451 INF TeslaSolarCharger.Server.Services.TelegramService] Can not send Telegram Message because botkey is empty.
teslasolarcharger  | [07-Apr-2024 17:16:33.431 WRN Microsoft.EntityFrameworkCore.Model.Validation] Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data; this mode should only be enabled during development.
teslasolarcharger  | [07-Apr-2024 17:16:33.992 ERR Microsoft.EntityFrameworkCore.Database.Connection] An error occurred using the connection to database 'teslamate' on server 'tcp://database:5432'.
teslasolarcharger  | [07-Apr-2024 17:16:34.044 ERR Microsoft.EntityFrameworkCore.Query] An exception occurred while iterating over the results of a query for context type 'TeslaSolarCharger.Model.EntityFramework.TeslamateContext'.
teslasolarcharger  | Npgsql.PostgresException (0x80004005): 28P01: password authentication failed for user "teslamate"
teslasolarcharger  |    at Npgsql.Internal.NpgsqlConnector.ReadMessageLong(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
teslasolarcharger  |    at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
teslasolarcharger  |    at Npgsql.Internal.NpgsqlConnector.AuthenticateSASL(List`1 mechanisms, String username, Boolean async, CancellationToken cancellationToken)
teslasolarcharger  |    at Npgsql.Internal.NpgsqlConnector.Authenticate(String username, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
teslasolarcharger  |    at Npgsql.Internal.NpgsqlConnector.<Open>g__OpenCore|213_1(NpgsqlConnector conn, SslMode sslMode, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken, Boolean isFirstAttempt)
teslasolarcharger  |    at Npgsql.Internal.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
teslasolarcharger  |    at Npgsql.PoolingDataSource.OpenNewConnector(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
teslasolarcharger  |    at Npgsql.PoolingDataSource.<Get>g__RentAsync|34_0(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
teslasolarcharger  |    at Npgsql.NpgsqlConnection.<Open>g__OpenAsync|42_0(Boolean async, CancellationToken cancellationToken)
teslasolarcharger  |    at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
teslasolarcharger  |    at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
teslasolarcharger  |    at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
teslasolarcharger  |    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
teslasolarcharger  |    at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
teslasolarcharger  |    at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
teslasolarcharger  |    at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
teslasolarcharger  |   Exception data:
teslasolarcharger  |     Severity: FATAL
teslasolarcharger  |     SqlState: 28P01
teslasolarcharger  |     MessageText: password authentication failed for user "teslamate"
teslasolarcharger  |     File: auth.c
teslasolarcharger  |     Line: 335
teslasolarcharger  |     Routine: auth_failed
```

I attched my docker-compose.yml...

Any ideas?
[docker-compose.yml.txt](https://github.com/pkuehnel/TeslaSolarCharger/files/14897806/docker-compose.yml.txt)
