### DISCUSSION TITLE
Enphase Enyoy S Metered Gateway

### DISCUSSION THREAD

**Discussion by ardent200** [pkuehnel/TeslaSolarCharger#1371] [Q&A] [answered]
Hello, I got a solar system from Enphase. I now wanted to use the great software TSC to charge my Tesla surplus store. I can also read the gateway out with the following API get command.

Command: curl -f -k -H "Accept:application/json" -H "Authorization:Bearer <mytoken>" -X GET https://10.0.0.xx/production.json

Result:  {"production":[{"type":"inverters","activeCount":15,"readingTime":1720612252,"wNow":2063,"whLifetime":146983},{"type":"eim","activeCount":1,"measurementType":"production","readingTime":1720612281,"wNow":1965.372,"whLifetime":145353.826,"varhLeadLifetime":2062.368,"varhLagLifetime":20318.825,"vahLifetime":189920.154,"rmsCurrent":8.885,"rmsVoltage":682.423,"reactPwr":-22.446,"apprntPwr":2023.417,"pwrFactor":0.97,"whToday":1867.826,"whLastSevenDays":104196.826,"vahToday":1658.154,"varhLeadToday":7.368,"varhLagToday":6.825}],"consumption":[{"type":"eim","activeCount":1,"measurementType":"total-consumption","readingTime":1720612281,"wNow":2067.593,"whLifetime":206749.762,"varhLeadLifetime":86880.648,"varhLagLifetime":-15735.973,"vahLifetime":212391.802,"rmsCurrent":9.392,"rmsVoltage":682.519,"reactPwr":-219.322,"apprntPwr":2116.826,"pwrFactor":0.97,"whToday":1944.762,"whLastSevenDays":48.762,"vahToday":1787.802,"varhLeadToday":250.648,"varhLagToday":113.0},{"type":"eim","activeCount":1,"measurementType":"net-consumption","readingTime":1720612281,"wNow":102.221,"whLifetime":62013.236,"varhLeadLifetime":88943.016,"varhLagLifetime":4582.853,"vahLifetime":212391.802,"rmsCurrent":0.507,"rmsVoltage":682.519,"reactPwr":-196.877,"apprntPwr":95.452,"pwrFactor":1.0,"whToday":0,"whLastSevenDays":0,"vahToday":0,"varhLeadToday":0,"varhLagToday":0}],"storage":[{"type":"acb","activeCount":0,"readingTime":0,"wNow":0,"whNow":0,"state":"idle"}]}%   

I tried to recreate the query in TSC under "Add Rest config" (see image below), unfortunately I was told there was a problem with the SSL connection.

Can someone please help me with what I entered incorrectly or how it should be correct. Thank you in advance.

Best Regards 

Markus

<img width="958" alt="Bildschirmfoto 2024-07-10 um 14 23 59" src="https://github.com/pkuehnel/TeslaSolarCharger/assets/175216616/2d236ea6-793a-4c83-b119-22a3fa0800bc">

**Comment by pkuehnel** [comment, marked as answer]
Is the SSL certificate a self signed certificate? If yes, add the follwing environment variable to your teslasolarcharger:

`      - IgnoreSslErrors=true `

Should look like this then:
```
  teslasolarcharger:
    image: pkuehnel/teslasolarcharger:latest
    container_name: teslasolarcharger
    logging:
        driver: "json-file"
        options:
            max-file: "10"
            max-size: "100m"
    restart: always
    depends_on:
      - teslamateapi
    environment:
#      - Serilog__MinimumLevel__Default=Verbose #uncomment this line and recreate container with docker compose up -d for more detailed logs
      - TZ=Europe/Berlin ##You can change your Timezone here
      - IgnoreSslErrors=true
    ports:
      - 7190:80
    volumes:
      - teslasolarcharger-configs:/app/configs
```

After that you need to rebuild (not only restart) the container using `docker compose up -d`. If that does not help, You need to share the error in your logs. Attention: **Possibly your token is in the logs.**
