### ISSUE TITLE
BLE API issues with configuration

### ISSUE THREAD

**Issue by Lord225** [pkuehnel/TeslaSolarCharger#1404]
Hello,
I'm unable to get bleapi to work properly.
Hardware: Raspberry Pi 4 (B)
I tried configuring it with the docker-compose provided in the README, but it throws a "connection refused" error. I had to create a network and set the driver to host. Now, I am able to reach the service.
```
  bleapi:
    image: ghcr.io/pkuehnel/teslasolarchargerbleapi:latest
    container_name: TeslaSolarChargerBleApi
    privileged: true
    restart: unless-stopped
    networks:
      - network
    environment:
      - ASPNETCORE_URLS=http://+:7210
    volumes:
      - /home/lord225/tscbleapi:/externalFiles
      - /var/run/dbus:/var/run/dbus
networks:
  network:
    driver: host
```
but unfortunately, it still displays an error message about hci not being able to crate socket. 
```
      Error: failed to find a BLE device: can't init hci: can't create socket: address family not supported by protocol
```
[ble-logs.txt](https://github.com/user-attachments/files/16329919/ble-logs.txt)
```
lord225@raspberrypi:~ $ systemctl status bluetooth
● bluetooth.service - Bluetooth service
     Loaded: loaded (/lib/systemd/system/bluetooth.service; enabled; preset: enabled)
     Active: active (running) since Sun 2024-07-21 17:14:13 CEST; 16h ago
       Docs: man:bluetoothd(8)
   Main PID: 5563 (bluetoothd)
     Status: "Running"
      Tasks: 1 (limit: 1576)
        CPU: 934ms
     CGroup: /system.slice/bluetooth.service
             └─5563 /usr/libexec/bluetooth/bluetoothd
```
```
lord225@raspberrypi:~ $ ls /var/run/dbus
containers  system_bus_socket
```
```
lord225@raspberrypi:~ $ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm
lord225@raspberrypi:~ $  uname -a
Linux raspberrypi 6.6.20+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.20-1+rpt1 (2024-03-07) aarch64 GNU/Linux
```
I also tried older images of bleapi but same result. I checked stack stuff from stack exchange but nothing seem to help mabe you can identify the issue & help to find solution.
