### ISSUE TITLE
Car power always 0W

### ISSUE THREAD

**Issue by MrBetatester** [pkuehnel/TeslaSolarCharger#144]
We have a Model 3 and Model Y both with a Wallbox Gen 3. The UI show the current grid power and some information about the cars but not the current charging value. It also not change the ampere. TeslaMate  TeslaMateApi show the needed values correctly.

![Screenshot_2022-07-15-14-28-01-88_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/33181024/179245974-615cec89-0290-43a2-be18-2293b3765469.jpg)

Thanks
Ronald

**Comment by pkuehnel** [comment]
Probably you did not set a Home Geofence? You have a Geofence as environment variable (default is 'Home') and you need to set this Geofence in TeslaMate UI with the name 'Home'.

**Comment by MrBetatester** [comment]
It was my fault. I checked TeslaMateApi response: "geofence":"Home " there was a space at the end of the name :-). Now it shows the current power but it doesn't control the loading process. 
I increased the SoC limit from 80 to 85 und more than the half of the needed power will be used from grid. I use the default update interval of 5 minutes but it doesn't stop loading after 20 minutes using grid power.

**Comment by pkuehnel** [comment]
Could you please share your `docker-compose.yml`? Please don't forget to remove your passwords before you share.

**Comment by MrBetatester** [comment]
I use port 4000 for teslamate, 4001 for teslamateapi and 4002 for teslaampsetter

```
version: "3"

services:
  teslamate:
    image: teslamate/teslamate:latest
    restart: always
    environment:
      - ENCRYPTION_KEY=##########################################################
      - DATABASE_USER=teslamate
      - DATABASE_PASS=##############################
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto
    ports:
      - 4000:4000
    volumes:
      - ./import:/opt/app/import
    cap_drop:
      - all

  database:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD=##############################
      - POSTGRES_DB=teslamate
    volumes:
      - teslamate-db:/var/lib/postgresql/data

  grafana:
    image: teslamate/grafana:latest
    restart: always
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=##############################
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
    ports:
      - 3000:3000
    volumes:
      - teslamate-grafana-data:/var/lib/grafana

  mosquitto:
    image: eclipse-mosquitto:2
    restart: always
    command: mosquitto -c /mosquitto-no-auth.conf
    # ports:
    #   - 1883:1883
    volumes:
      - mosquitto-conf:/mosquitto/config
      - mosquitto-data:/mosquitto/data


  teslamateapi:
    image: tobiasehlert/teslamateapi:latest
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"
    restart: always
    depends_on:
      - database
    environment:
      - DATABASE_USER=teslamate
      - DATABASE_PASS=##############################
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto
      - TZ=Europe/Berlin
      - ENABLE_COMMANDS=true
      - COMMANDS_ALL=true
      - API_TOKEN_DISABLE=true
    ports:
      - 4001:8080

  smartteslaampsetter:
    image: pkuehnel/smartteslaampsetter:latest
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"
    restart: always
    depends_on:
      - teslamateapi
    environment:
      - CurrentPowerToGridUrl=http://192.168*.*/pv_tesla/GridPower.php
      #- CurrentInverterPowerUrl=http://192.168*.*/pv_tesla/InverterPower.php
      - TeslaMateApiBaseUrl=http://192.168*.*:4001
      - UpdateIntervalSeconds=30
      - CarPriorities=1|2
      - GeoFence=Home
      - MinutesUntilSwitchOn=5
      - MinutesUntilSwitchOff=5
      - PowerBuffer=0
      - TZ=Europe/Berlin
    ports:
      - 4002:80
    volumes:
      - teslaampsetter-configs:/app/configs

volumes:
  teslamate-db:
  teslamate-grafana-data:
  mosquitto-conf:
  mosquitto-data:
  teslaampsetter-configs:

```
